80 colidable system
R-Type-Epitech-Nantes/R-Type pull request #111
Opened 2022-10-11 20:37 UTC by 31Nathan

Adding a collidable system
Maximum optimization to not check twice the same entities

2022-10-11 23:04 UTC, LucasTesnier requested changes
Some recommendation, otherwise very good job

2022-10-11 23:04 UTC, LucasTesnier commented on tests/unit_tests/libs_tests/ECS_tests/Systems_tests/CMakeLists.txt
> +    ${SRC_ROOT}/CollidableSystemTest.cpp
match you file case

2022-10-12 07:39 UTC, LucasTesnier approved these changes

2022-10-12 15:35 UTC, TomDUVAL-MAHE commented on libs/GameSystems/CollidableSystem.hpp
> +    /// Needed Component : Collidable, Position, Size, Damage
Good !

2022-10-12 15:37 UTC, TomDUVAL-MAHE submitted a review, later dismissed

2022-10-12 16:58 UTC, ZQUEMA requested changes
The logic is good but some functions should be move in a source file

2022-10-12 16:58 UTC, ZQUEMA commented on libs/GameSystems/CollidableSystem.hpp
> +    /// Needed Component : Collidable, Position, Size, Damage
I like It

2022-10-12 16:58 UTC, ZQUEMA commented on libs/GameSystems/CollidableSystem.hpp
> +        bool isSameWidth(Position &fstPos, Position &sndPos, Size &fstSize, Size &sndSize)
Please put it in a source (.cpp) file or add the inline mention

2022-10-12 16:58 UTC, ZQUEMA commented on libs/GameSystems/CollidableSystem.hpp
> +        bool isSameHeight(Position &fstPos, Position &sndPos, Size &fstSize, Size &sndSize)
Please put it in a source (.cpp) file or add the inline mention

2022-10-12 16:58 UTC, ZQUEMA commented on libs/GameSystems/CollidableSystem.hpp
> +        void collide(
Please put it in a source (.cpp) file or add the inline mention

2022-10-12 16:58 UTC, ZQUEMA commented on libs/GameSystems/CollidableSystem.hpp
> +            for (std::shared_ptr<ecs::Entity> fstEntity : fstEntities) {
Nope you can directly precise the type and it's the best option

2022-10-12 16:58 UTC, ZQUEMA commented on libs/GameSystems/CollidableSystem.hpp
> +        void allyCollide(std::vector<std::shared_ptr<ecs::Entity>> &allyEntities,
Please put it in a source (.cpp) file or add the inline mention

2022-10-12 16:58 UTC, ZQUEMA commented on libs/GameSystems/CollidableSystem.hpp
> +        void enemyCollide(std::vector<std::shared_ptr<ecs::Entity>> &enemiesProjectiles,
Please put it in a source (.cpp) file or add the inline mention

2022-10-12 16:58 UTC, ZQUEMA commented on libs/GameSystems/CollidableSystem.hpp
> +        inline void run(World &world) override final
Please put it in a source (.cpp) file

2022-10-12 16:59 UTC, LucasTesnier requested changes
Non inline function -> CPP

2022-10-12 21:36 UTC, LucasTesnier submitted a review, later dismissed
NTR!

2022-10-12 22:02 UTC, LucasTesnier approved these changes

2022-10-12 22:51 UTC, ZQUEMA approved these changes

2022-10-13 06:44 UTC, merged