107 implement transisthor for ressource entities
R-Type-Epitech-Nantes/R-Type pull request #112
Opened 2022-10-11 22:52 UTC by LucasTesnier

Implement Entity transit operation (Cast / Uncast)

Use it inside Communicator.

Change RFC for Entity transfer.

Add unit and functional testing for this functionality.

2022-10-11 23:03 UTC, 31Nathan approved these changes
Need another review

2022-10-12 11:56 UTC, 31Nathan approved these changes
LGTM!

2022-10-12 16:40 UTC, ZQUEMA requested changes
Some changes are needed.

2022-10-12 16:40 UTC, ZQUEMA commented on libs/Transisthor/Transisthor.hpp
>          void *transitEcsDataToNetworkData(
Add inline mention

2022-10-12 16:40 UTC, ZQUEMA commented on libs/Transisthor/Transisthor.hpp
> +        /// transferehttps://tekfeed.epitech.eu/#/universite/38/categorie/courses-for-epitech-studentsd resource
I don’t think your college research should be here;)

2022-10-12 16:40 UTC, ZQUEMA commented on libs/Transisthor/Transisthor.hpp
> +        void *transitEcsDataToNetworkDataEntity(
Add inline mention or transfert to a cpp file

2022-10-12 16:40 UTC, ZQUEMA commented on libs/Transisthor/Transisthor.hpp
> +        void *transitEcsDataToNetworkDataEntityAlliedProjectile(
Add inline mention or transfert it into a cpp file

2022-10-12 16:40 UTC, ZQUEMA commented on libs/Transisthor/Transisthor.hpp
> +        void *transitEcsDataToNetworkDataEntityEnemy(
Add inline mention or transfert it into a cpp file

2022-10-12 16:40 UTC, ZQUEMA commented on libs/Transisthor/Transisthor.hpp
> +        void *transitEcsDataToNetworkDataEntityEnemyProjectile(
Add inline mention or transfert it into a cpp file

2022-10-12 16:40 UTC, ZQUEMA commented on libs/Transisthor/Transisthor.hpp
> +        void *transitEcsDataToNetworkDataEntityObstacle(
Add inline mention or transfert it into a cpp file

2022-10-12 16:40 UTC, ZQUEMA commented on libs/Transisthor/Transisthor.hpp
> +        void *transitEcsDataToNetworkDataEntityPlayer(
Add inline mention or transfert it into a cpp file

2022-10-12 16:40 UTC, ZQUEMA commented on libs/Transisthor/Transisthor.hpp
> +        void *transitEcsDataToNetworkDataEntityProjectile(unsigned short id, int posX, int posY, double velAbsc,
Add inline mention or transfert it into a cpp file

2022-10-12 17:00 UTC, ZQUEMA approved these changes
OK

2022-10-12 18:28 UTC, TomDUVAL-MAHE approved these changes
NTR

2022-10-12 19:02 UTC, merged