137 rebase entity transfer protocol
R-Type-Epitech-Nantes/R-Type pull request #138
Opened 2022-10-13 20:40 UTC by LucasTesnier

WILL BE UPDATED.

2022-10-13 20:46 UTC, ZQUEMA submitted a review, later dismissed

2022-10-13 20:46 UTC, ZQUEMA commented on libs/Transisthor/Transisthor.hpp
> +        /// @param allyId Id of the allied who fired
allied -> ally ?

2022-10-14 01:03 UTC, TomDUVAL-MAHE requested changes

2022-10-14 01:03 UTC, TomDUVAL-MAHE commented on libs/Transisthor/Transisthor.hpp
> +        /// @param enemyId If of the enemy who fired
If of ???

2022-10-14 01:17 UTC, TomDUVAL-MAHE approved these changes

2022-10-14 02:51 UTC, ZQUEMA approved these changes

2022-10-14 02:51 UTC, merged