135 some namespaces attributions has to be reviewed
R-Type-Epitech-Nantes/R-Type pull request #200
Opened 2022-10-23 13:19 UTC by ZQUEMA

close #135

2022-10-23 21:31 UTC, 31Nathan requested changes

2022-10-23 21:31 UTC, 31Nathan commented on libs/Transisthor/ECSLogic/Client/Systems/SendNewlyCreatedToServer.hpp
> +#include "World/World.hpp"
Missing jumpline

2022-10-23 21:31 UTC, 31Nathan commented on libs/Transisthor/ECSLogic/Server/Systems/SendToClient.hpp
> +
Useless empty line

2022-10-24 06:18 UTC, osvegn requested changes
Too much file with the same error, please update all file I had comment and update others that have this error

2022-10-24 06:18 UTC, osvegn commented on libs/GraphicECS/SFML/Systems/InputManagement.cpp
> +        std::queue<std::pair<graphic::sfml::ActionQueueComponent::inputAction_e, float>> &actions =
don't use "graphic::sfml" if you write "using namespace graphic::sfml" at the beginning of the file

2022-10-24 06:18 UTC, osvegn commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateAlliedProjectile.hpp
> +using namespace ecs;
Useless

2022-10-24 06:18 UTC, osvegn commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateAlliedProjectile.hpp
> +namespace rtypelogic::entitymanipulation
update the comment at the end of the namespace

2022-10-24 06:18 UTC, osvegn commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateBackground.hpp
> +namespace rtypelogic::entitymanipulation
update the comment at the end of the namespace

2022-10-24 06:18 UTC, osvegn commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateBackground.hpp
> +using namespace ecs;
Useless

2022-10-24 06:18 UTC, osvegn commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateButton.hpp
> +namespace rtypelogic::entitymanipulation
update the comment at the end of the namespace

2022-10-24 06:18 UTC, osvegn commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateButton.hpp
> +using namespace ecs;
Useless

2022-10-24 06:18 UTC, osvegn commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemy.hpp
> +using namespace ecs;
Useless

2022-10-24 06:18 UTC, osvegn commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemy.hpp
> +namespace rtypelogic::entitymanipulation
update the comment at the end of the namespace

2022-10-24 06:18 UTC, osvegn commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemyProjectile.hpp
> +using namespace ecs;
Useless

2022-10-24 06:18 UTC, osvegn commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemyProjectile.hpp
> +namespace rtypelogic::entitymanipulation
update the comment at the end of the namespace

2022-10-24 06:18 UTC, osvegn commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateObstacle.hpp
> +using namespace ecs;
Useless

2022-10-24 06:18 UTC, osvegn commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateObstacle.hpp
> +namespace rtypelogic::entitymanipulation
update the comment at the end of the namespace

2022-10-24 06:18 UTC, osvegn commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreatePlayer.hpp
> +using namespace ecs;
Useless

2022-10-24 06:18 UTC, osvegn commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreatePlayer.hpp
> +namespace rtypelogic::entitymanipulation
update the comment at the end of the namespace

2022-10-27 07:42 UTC, closed without merging