201 fix lifetime system
R-Type-Epitech-Nantes/R-Type pull request #207
Opened 2022-10-24 13:28 UTC by 31Nathan

The decrease lifetime system is now implemented
Add security to the death system

2022-10-24 13:31 UTC, LucasTesnier approved these changes

2022-10-24 15:52 UTC, LucasTesnier submitted a review, later dismissed
Amazing

2022-10-24 21:55 UTC, osvegn requested changes
There is less tests coverage, you can improve them to make them at least equal to the previous coverage percentage

2022-10-25 07:23 UTC, LucasTesnier approved these changes

2022-10-25 12:01 UTC, merged