Make shared resources usable in threads
R-Type-Epitech-Nantes/R-Type pull request #239
Opened 2022-10-27 15:54 UTC by ZQUEMA

## Purpose:
At the end of this issues, a shared resource must be usable in threads. This means that it can only be used and modified by only one thread at a time.

## Added features
- The Resource class can now be locked when used or modified in threads.

This will close #238

2022-10-27 16:32 UTC, LucasTesnier approved these changes

2022-10-27 19:20 UTC, osvegn requested changes
One change in the documentation to do

2022-10-27 19:20 UTC, osvegn commented on libs/ECS/Resource/Resource.hpp
> +    /// The std::mutex inheritance is in order to allows to lock a Resource when something wants to use/modify it
> to allow

2022-10-28 07:56 UTC, 31Nathan approved these changes

2022-10-28 08:05 UTC, LucasTesnier approved these changes

2022-10-28 12:29 UTC, osvegn approved these changes

2022-10-28 13:13 UTC, merged