Lock the entities when they are used
R-Type-Epitech-Nantes/R-Type pull request #252
Opened 2022-10-28 08:36 UTC by ZQUEMA

## Purpose:
At the end of this issues, an entity have to be locked before it can be used or modified. This issue prepares the future thread pool which will be implemented later.

## Updated features:
- Lock the entities in the systems in the library SFMLGraphicECS

This will close #237

2022-10-28 13:11 UTC, LucasTesnier approved these changes

2022-10-28 13:46 UTC, LucasTesnier approved these changes

2022-10-28 19:29 UTC, 31Nathan requested changes

2022-10-28 19:31 UTC, TomDUVAL-MAHE approved these changes
NTR

2022-10-28 19:33 UTC, ZQUEMA commented on libs/Transisthor/Transisthor.cpp
> +#include "R-TypeLogic/Server/Components/AfkFrequencyComponent.hpp"
The format moved it. Before it was above.

2022-10-28 19:57 UTC, 31Nathan submitted a review, later dismissed

2022-10-29 08:25 UTC, LucasTesnier approved these changes

2022-10-29 08:33 UTC, osvegn approved these changes
Look good

2022-10-29 08:34 UTC, merged