147 implement switch to room protocol
R-Type-Epitech-Nantes/R-Type pull request #263
Opened 2022-10-29 17:54 UTC by LucasTesnier

Rebase of the Hub, Lobby and Room system.

Hub implementation :
- At his creation, the server know handle a hub global loop, which interacts with a communicator instance.
- The hub can handle several clients and dispatch them to different rooms in terms of theirs request.
- Hub can also handle player disconnection / refusal when no places left (or missing performance)

Lobby rebase :
- At his creation a client is now connected to a hub. He receive the list of all the active rooms (Id + name) and can choose to create / join one of this room.
- Client can now create a room and joined it instantly by specifying name of the newly created room. 
- Client can now join a current room by specifying the wanted room id.
- Protocol 2X of communicator is now fully used and the network is switched correctly.

Room rebase :
- At creation, two rooms is available.
- A room need to have a name of strictly 10 characters.
- When a new room is add inside the server, a empty port is now automatically binded.
- Some verification (Like bad ID, same Name, etc...) is implemented to protect the server integrity.
- Everything is now setup to add a graphical interface for replacing the textual one.

WARNING : When this PR's will be merged, multiple client connection and server SigInt will be not functional. This is normal. Everything is gonna return at normal when the rooming process issue will be done.

Enjoy your new triple AAA game ! :)

2022-10-29 18:24 UTC, 31Nathan requested changes

2022-10-29 18:24 UTC, 31Nathan commented on Server/Server.cpp
> +        roomName[i] = tempRoomName[i];
strcpy ?

2022-10-29 18:24 UTC, 31Nathan commented on Server/Server.hpp
> +        /// @param actual port number (+ 100 per iteration)
In the function it's +101

2022-10-29 18:24 UTC, 31Nathan commented on Server/main.cpp
> +    server.createANewRoom("SleepLucas");
No better Name? xD

2022-10-29 18:35 UTC, ZQUEMA requested changes
Answer to the questions

2022-10-29 18:35 UTC, ZQUEMA commented on Server/Room.hpp
> +    inline bool operator==(const Room &left, const std::string &right) { return ((left.getRoomName() == right)); }
Can we compare 2 Rooms ?

2022-10-29 18:35 UTC, ZQUEMA commented on Server/Server.hpp
> +        /// @brief Handle a connection request. Send all rooms informations (id + name) to the client.
What is the protocol used here ?

2022-10-29 18:35 UTC, ZQUEMA commented on Server/main.cpp
> +    server.createANewRoom("SleepLucas");
Nice reference

2022-10-30 08:06 UTC, LucasTesnier commented on Server/Server.hpp
> +        /// @brief Handle a connection request. Send all rooms informations (id + name) to the client.
Well done

2022-10-30 08:07 UTC, LucasTesnier commented on Server/Room.hpp
> +    inline bool operator==(const Room &left, const std::string &right) { return ((left.getRoomName() == right)); }
:eyes:

2022-10-30 08:08 UTC, LucasTesnier commented on Server/Server.hpp
> +        /// @param actual port number (+ 100 per iteration)
ooops

2022-10-30 08:08 UTC, LucasTesnier commented on Server/main.cpp
> +    server.createANewRoom("SleepLucas");
Absolutly not :)

2022-10-30 08:11 UTC, LucasTesnier commented on Server/Server.cpp
> +        roomName[i] = tempRoomName[i];
Not working for char * to std::string

2022-10-30 08:25 UTC, 31Nathan approved these changes

2022-10-30 10:38 UTC, TomDUVAL-MAHE commented on Server/Room.hpp
> +    inline bool operator==(const Room &left, const std::string &right) { return ((left.getRoomName() == right)); }
:laughing:

2022-10-30 10:39 UTC, TomDUVAL-MAHE approved these changes

2022-10-30 16:13 UTC, ZQUEMA approved these changes

2022-10-30 16:14 UTC, merged