264 animate a player
R-Type-Epitech-Nantes/R-Type pull request #265
Opened 2022-10-29 19:44 UTC by osvegn

## New features
- Use animation system and components to animate the player.
- Load new texture for the player animation.
- Create new textureName enumerator.
- Use animationComponent and AnimationFrequencyComponent instead of textureName on player to animate him.
## Updated features
- Use an index to store actual position during the animation in AnimationComponent.
- Update AnimationFrequencyComponent documentation.
- Change default value for the AnimationFrequencyComponent frequency.
## Fixed features
- Fix crash in AnimationSystem

2022-10-29 20:15 UTC, ZQUEMA requested changes
Lock every resources and it will be good for me

2022-10-29 20:15 UTC, ZQUEMA commented on libs/GraphicECS/SFML/Systems/AnimationSystem.cpp
>          entity->getComponent<AnimationFrequencyComponent>().frequency -= std::chrono::duration<double>(world.getResource<GameClock>().getElapsedTime());
You must lock every resources

2022-10-29 20:15 UTC, ZQUEMA commented on libs/GraphicECS/SFML/Systems/AnimationSystem.cpp
>              texturesMap textures = world.getResource<GraphicsTextureResource>()._texturesList;
You must lock every resources

2022-10-29 20:36 UTC, ZQUEMA requested changes
Some other changes are required

2022-10-29 20:36 UTC, ZQUEMA commented on libs/GraphicECS/SFML/Systems/AnimationSystem.cpp
> +            auto guard = std::lock_guard(world.getResource<GameClock>());
Please, put the resource in a variable. That's one less action

2022-10-29 20:36 UTC, ZQUEMA commented on libs/GraphicECS/SFML/Systems/AnimationSystem.cpp
> +                auto guard = std::lock_guard(world.getResource<GraphicsTextureResource>());
Please, put the resource in a variable. That's one less action

2022-10-29 20:36 UTC, ZQUEMA commented on libs/GraphicECS/SFML/Systems/AnimationSystem.cpp
> +            auto guard = std::lock_guard(world.getResource<GameClock>());
rename the variable `auto guard`. it has the same name as the one just above.

2022-10-29 20:36 UTC, ZQUEMA commented on libs/GraphicECS/SFML/Systems/AnimationSystem.cpp
> +                auto guard = std::lock_guard(world.getResource<GraphicsTextureResource>());
rename the variable auto guard. it has the same name as the others  just above.

2022-10-29 21:13 UTC, 31Nathan requested changes

2022-10-29 21:13 UTC, 31Nathan commented on libs/GraphicECS/SFML/Systems/DrawComponents.cpp
> +                if (layerType.layer == LayerLvL::layer_e::PLAYER) {
Please Make a function

2022-10-29 21:15 UTC, ZQUEMA approved these changes

2022-10-29 21:20 UTC, osvegn commented on libs/GraphicECS/SFML/Systems/DrawComponents.cpp
> +                if (layerType.layer == LayerLvL::layer_e::PLAYER) {
It will be improved in #270

2022-10-30 03:18 UTC, TomDUVAL-MAHE approved these changes

2022-10-30 08:26 UTC, 31Nathan submitted a review, later dismissed
Do not forget to make functions ^^

2022-10-30 10:40 UTC, TomDUVAL-MAHE approved these changes

2022-10-30 11:27 UTC, 31Nathan approved these changes
LGTM

2022-10-30 11:28 UTC, merged