275 add authentication system
R-Type-Epitech-Nantes/R-Type pull request #284
Opened 2022-10-31 15:01 UTC by LucasTesnier

Add a name and password variable inside ClientRoom class.

Implement the name and password transfer inside network protocol.

Prepare for auth action with the database inside Room classes.

Add a moving text above the player head.

Update outdated unit testing.

2022-10-31 15:04 UTC, TomDUVAL-MAHE submitted a review, later dismissed
NTR

2022-10-31 15:26 UTC, 31Nathan requested changes

2022-10-31 15:26 UTC, 31Nathan commented on tests/unit_tests/Transisthor_tests/Transisthor_tests.cpp
> +        entityId, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, false, 2, "Lucas", std::string(""), {0});
Same here

2022-10-31 18:15 UTC, 31Nathan approved these changes

2022-11-01 12:17 UTC, ZQUEMA approved these changes

2022-11-01 12:19 UTC, merged