232 fix multiple input bug
R-Type-Epitech-Nantes/R-Type pull request #285
Opened 2022-11-01 08:34 UTC by osvegn

## Updated features
- Refacto InputManagement
## Fixed features
- Multiple input bug

2022-11-01 08:40 UTC, 31Nathan requested changes

2022-11-01 08:40 UTC, 31Nathan commented on libs/GraphicECS/SFML/Systems/InputManagement.hpp
> +        void shoot(World &world);
Documentation missing

2022-11-01 12:19 UTC, LucasTesnier submitted a review, later dismissed
SGTM

2022-11-01 12:29 UTC, ZQUEMA requested changes
Please answer to the comments

2022-11-01 12:29 UTC, ZQUEMA commented on libs/GraphicECS/SFML/Systems/InputManagement.cpp
> +                        auto guard = std::lock_guard(random);
Perhaps you should place this lock just before the for loop, in a different scope. It's a little more optimized.
Or use .lock() and .unlock() before and after the loop

2022-11-01 12:29 UTC, ZQUEMA commented on libs/GraphicECS/SFML/Systems/InputManagement.cpp
> +            if (action > 1 && !(p->contains<IsShootingComponent>())) {
Perhaps you should place the lock in the for scope and not in the if scope because in both cases, you are locking the entity

2022-11-02 11:53 UTC, LucasTesnier approved these changes

2022-11-02 12:59 UTC, ZQUEMA approved these changes

2022-11-02 13:52 UTC, merged