276 add patterns to enemies
R-Type-Epitech-Nantes/R-Type pull request #295
Opened 2022-11-02 22:05 UTC by 31Nathan

This PR will implement patterns for enemies corresponding to their types
Each pattern is described in the following file: EnemyPatterns.cpp

2022-11-05 22:34 UTC, 31Nathan commented on libs/R-TypeLogic/Server/Systems/EnemiesPatterns.cpp
> +    //     if (x + 1 < nbEnemies) {
@osvegn

2022-11-06 17:56 UTC, LucasTesnier requested changes
Some doc, typo and question, otherwise Masterclass

2022-11-06 17:56 UTC, LucasTesnier commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemy.cpp
> +            RandomDevice &random = world.getResource<RandomDevice>();
Check discord

2022-11-06 17:56 UTC, LucasTesnier commented on libs/R-TypeLogic/Server/Systems/EnemiesPatterns.cpp
> +/// @brief  Init the Ice Pattern (hord squared shape pattern)
Double space

2022-11-06 17:56 UTC, LucasTesnier commented on libs/R-TypeLogic/Server/Systems/EnemiesPatterns.cpp
> +/// @brief  Apply the Ice Pattern (hord squared shape pattern)
Double space

2022-11-06 17:56 UTC, LucasTesnier commented on libs/R-TypeLogic/Server/Systems/EnemiesPatterns.cpp
> +
Useless empty line

2022-11-06 17:56 UTC, LucasTesnier commented on libs/R-TypeLogic/Server/Systems/EnemiesPatterns.cpp
> +        {
What ????

2022-11-06 18:13 UTC, TomDUVAL-MAHE requested changes

2022-11-06 18:13 UTC, TomDUVAL-MAHE commented on libs/R-TypeLogic/Global/Systems/ElectricInvisibleEnemySystem.cpp
> +using namespace ecs;
It's not R-TypeLogic::Global::Systems ?

2022-11-06 18:13 UTC, TomDUVAL-MAHE commented on libs/R-TypeLogic/Global/Systems/ElectricInvisibleEnemySystem.hpp
> +namespace ecs
It's not R-TypeLogic::Global::Systems ?

2022-11-06 18:13 UTC, TomDUVAL-MAHE commented on libs/R-TypeLogic/Server/Systems/EnemiesPatterns.cpp
> +using namespace ecs;
It's not R-TypeLogic::Server::Systems ?

2022-11-06 18:13 UTC, TomDUVAL-MAHE commented on libs/R-TypeLogic/Server/Systems/EnemiesPatterns.hpp
>  namespace ecs
Same as other comment ?

2022-11-06 20:21 UTC, LucasTesnier approved these changes

2022-11-06 21:05 UTC, TomDUVAL-MAHE approved these changes

2022-11-06 21:11 UTC, merged