327 create a boss
R-Type-Epitech-Nantes/R-Type pull request #332
Opened 2022-11-07 22:29 UTC by 31Nathan

At the end of level four, we do have a boss
The boss generates little mobs named "pawns" with reduced life, damage, etc... but keeping the same projectile

2022-11-07 22:40 UTC, osvegn approved these changes

2022-11-07 22:45 UTC, osvegn approved these changes

2022-11-07 22:50 UTC, ZQUEMA requested changes
Spawn ?

2022-11-07 22:50 UTC, ZQUEMA commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemy.cpp
> +    std::size_t createBossPawn(World &world, Position &pos, unsigned int pawnType, const unsigned short networkId)
Is that normal `createBossPawn` instead of `createBossSpawn` ?

2022-11-07 22:50 UTC, ZQUEMA commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemy.hpp
> +    std::size_t createBossPawn(World &world, Position &pos, unsigned int pawnType, const unsigned short networkId = 0);
Is that normal `createBossPawn` instead of `createBossSpawn` ?

2022-11-07 22:50 UTC, ZQUEMA commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemy.hpp
> +    /// @brief This function creates a boss pawn with corresponding caracteristics, everything is reduced except the projectiles
spawn ?

2022-11-07 22:50 UTC, ZQUEMA commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemy.hpp
> +    /// @param world the world where the pawn will be created
spawn ?

2022-11-07 22:50 UTC, ZQUEMA commented on libs/R-TypeLogic/EntityManipulation/CreateEntitiesFunctions/CreateEnemy.hpp
> +    /// @param pawnType the type of the generated pawn (between BASIC and ELECTRIC)
spawnType ?

2022-11-07 22:50 UTC, ZQUEMA commented on libs/R-TypeLogic/Server/Systems/EnemiesPatterns.cpp
> +/// @param boss the boss of the level, following his pawns patterns
spawn ?

2022-11-07 23:00 UTC, ZQUEMA submitted a review, later dismissed

2022-11-07 23:21 UTC, TomDUVAL-MAHE approved these changes

2022-11-08 08:03 UTC, osvegn approved these changes

2022-11-08 08:07 UTC, LucasTesnier approved these changes

2022-11-08 10:08 UTC, merged