50 implement switch protocol communicator
R-Type-Epitech-Nantes/R-Type pull request #56
Opened 2022-10-01 16:49 UTC by LucasTesnier

Finish the development of the communicator.

Implement and rebase the data transfer protocol :
- Unify the header identification and production process
- Add a new data inside the header (Data type)
- Fix some misunderstanding with the header memory manipulation
- Add malloc verification

Implement data type management :
- Add basic data type (10 -> Connection, 30 -> ECS) (Documentation will be added inside the RFC in future)
- Add intern data type (20 -> Kick/Rebase operation, 21 -> Answer of the 20) (Documentation will be added inside the RFC in future)

Implement functional testing :
- Add a simulation of three Communicator interacting with each other (Some other scripting test will be added in the future)

Fix an oversight inside the communicator utility function:
- Add a bridge between Communicator and sender module to sends some data.

The Communicator is now able to tell another Communicator to change his interlocutor.

2022-10-02 10:35 UTC, 31Nathan approved these changes
Seems good to me, although I have some difficulties understanding the network

2022-10-02 16:46 UTC, osvegn commented
@LucasTesnier
Is there an issue (or some issues) with functionality or documentation you want to implement in the future ? Otherwise, please do it.

2022-10-02 17:05 UTC, osvegn requested changes
Remove the Client class destructor in the header file and set it to default.
Some documentation to improve.

2022-10-02 17:05 UTC, osvegn commented on libs/Communicator/Receiver.hpp
> +        void dataTraitmentType30(Message dataContent);
> trait the data

It's not precise enough. It seems these function "add message" somewhere, it's more precise than "trait data".

2022-10-03 08:10 UTC, LucasTesnier commented on libs/Communicator/Communicator.cpp
> +        _senderModule.sendDataToAClient(client, (void *)"kick", 5, 30); /// TO REFACTO WHEN UDP PROTOCOL IS IMPLEMENTED
https://github.com/R-Type-Epitech-Nantes/R-Type/issues/60

2022-10-03 08:12 UTC, 31Nathan approved these changes

2022-10-03 12:21 UTC, osvegn approved these changes
All right

2022-10-03 13:19 UTC, merged